export const errorMessages = {
  LOGIN_RATE_LIMITED: '登录尝试过于频繁，请稍后再试。',
  VALIDATION_ERROR: '输入内容不符合要求，请检查必填项、时间和分值精度。',
  CONFLICT: '数据已发生变化或与现有记录冲突，请刷新后重试。',
  GRADE_VERSION_CONFLICT: '评分已有新版本，请刷新并核对后重新更正。',
  DRAFT_VERSION_CONFLICT: '草稿已被其他操作更新，请重新打开编辑。',
  UNAUTHENTICATED: '登录已过期，请重新登录。',
  FORBIDDEN: '当前账号没有此操作权限。',
  INVALID_STATE: '作业尚未进入允许操作的阶段，请刷新查看当前状态。',
  RESULTS_ALREADY_PUBLISHED: '成绩已发布，不能再修改评分。',
  ASSIGNMENT_NOT_DRAFT: '只有草稿作业可以编辑或删除。',
  ASSIGNMENT_HAS_SUBMISSIONS: '作业已有提交或运行记录，不能编辑或删除。',
  SUBMISSION_NOT_VALID: '仅可为材料检查通过的有效提交评分。',
  GRADE_EXISTS_USE_CORRECTION: '评分已存在，请刷新后通过更正流程处理。',
  LOCK_CURRENT_GRADE_BEFORE_CORRECTION: '当前版本尚未锁定，请先核对并锁定。',
  ONLY_LATEST_GRADE_CAN_BE_LOCKED: '已有更新的评分版本，请刷新后核对。',
  ALL_RUBRIC_ITEMS_REQUIRED_ONCE: '请填写全部评分项，每项只提交一次。',
  RUBRIC_SCORE_OUT_OF_RANGE: '评分不能超过该项满分。',
  PANEL_NOT_READY: '请先保存两个方向相反、每组五人的评审组。',
  REVIEWER_NOT_IN_REVIEWER_CLASS:
    '评审人必须只属于指定评审班，不能同时在目标班。',
  REVIEWER_CLASS_CONFLICT: '评审人的班级归属发生冲突，请检查名单。',
  MATERIAL_CHECKS_PENDING: '仍有提交未完成材料检查，请等待检查结果。',
  SUBMISSION_DEADLINE_NOT_REACHED: '尚未到提交截止时间。',
  ANOMALY_NOT_OPEN_OR_NOT_FOUND: '这条异常已被处理，请刷新查看结论。',
  CLASS_ALREADY_EXISTS: '相同学期内已存在同名班级。',
  STUDENT_IDENTITY_CONFLICT:
    '学号已存在，但姓名或账号角色不匹配；导入已全部回滚。',
  NEW_STUDENT_PASSWORD_REQUIRED:
    '新账号必须填写至少10位初始密码；导入已全部回滚。',
  ENROLLMENT_IN_USE: '该学生已参与评审组或有提交记录，不能移出班级。',
  DEADLINE_MUST_BE_EXTENDED: '新截止时间必须晚于原时间和当前时间。',
  PUBLICATION_BLOCKED: '尚未满足发布条件，请处理页面列出的阻塞项。',
  NO_VALID_SUBMISSIONS: '没有可发布成绩的有效提交。',
  LATEST_GRADE_NOT_LOCKED: '最新教师评分未锁定',
  AGGREGATE_NOT_READY: '聚合结果尚未生成',
  TEACHER_SCORE_OUT_OF_RANGE: '教师评分数据超出量表范围，需要核查',
  AGGREGATE_OUT_OF_RANGE: '聚合分超出量表范围',
  AGGREGATE_STALE: '评审已更新，需要重新聚合',
  REVIEWS_INCOMPLETE: '五人评审尚未全部完成',
  MATERIAL_NOT_VALID: '材料检查尚未通过',
  OPEN_ANOMALIES_REQUIRE_REVIEW: '还有异常需要教师复核',
}
