export const errorMessages = {
  TOPIC_ALREADY_CLAIMED:
    '此知识点已被学生认领，不能修改或删除。请新增另一个条目。',
  PROGRAMMING_PROBLEM_NOT_READY: '请先补齐题目说明、公开样例和隐藏测试用例。',
  FINAL_PROJECT_REQUIRED: '此操作只适用于期末微课作业。',
  MATERIAL_NOT_FOUND: '材料文件不存在或已不可用，请核对上传记录。',
  ANONYMOUS_MATERIAL_NOT_READY: '匿名材料仍在核验中，暂不可下载。',
  REVIEW_MATERIAL_MUST_BE_OPENED: '请先下载匿名材料，系统才能开始记录评审。',
  REVIEW_DEADLINE_PASSED: '评审截止时间已过，不能再提交评分。',
  UNSAFE_ARCHIVE_ENTRY: '此材料无法安全读取，请核对压缩包。',
  FINAL_REVIEW_NOT_READY: '请等待两组评审聚合完成后，再录入复核最终分。',
  FINAL_REVIEW_ALREADY_LOCKED: '复核最终分已锁定，请刷新查看已保存的记录。',
  FINAL_REVIEW_SCORE_OUT_OF_RANGE: '复核最终分不能超过量表满分。',
  HIGH_RISK_REVIEW_NOT_FOUND: '当前作品不需要高风险复核，请刷新状态。',
  TEACHER_FINAL_REVIEW_REQUIRED: '高风险作品需要教师锁定复核最终分',
  HIGH_RISK_REQUIRES_FINAL_REVIEW: '请到评分工作台录入复核最终分。',
  FINAL_REVIEW_PREVENTS_REAGGREGATION:
    '已存在锁定的复核最终分，不能用新的评审输入重新聚合。',
  LOGIN_RATE_LIMITED: '登录尝试过于频繁，请稍后再试。',
  VALIDATION_ERROR: '输入内容不符合要求，请检查必填项、时间和分值精度。',
  CONFLICT: '数据已发生变化或与现有记录冲突，请刷新后重试。',
  GRADE_VERSION_CONFLICT: '评分已有新版本，请刷新并核对后重新更正。',
  DRAFT_VERSION_CONFLICT: '草稿已被其他操作更新，请重新打开编辑。',
  UNAUTHENTICATED: '登录已过期，请重新登录。',
  FORBIDDEN: '当前账号没有此操作权限。',
  INVALID_STATE: '作业尚未进入允许操作的阶段，请刷新查看当前状态。',
  RESULTS_ALREADY_PUBLISHED: '成绩已发布，不能再修改评分。',
  ASSIGNMENT_NOT_DRAFT: '只有草稿作业可以编辑或删除。',
  ASSIGNMENT_HAS_SUBMISSIONS: '作业已有提交或运行记录，不能编辑或删除。',
  SUBMISSION_NOT_VALID: '仅可为材料检查通过的有效提交评分。',
  GRADE_EXISTS_USE_CORRECTION: '评分已存在，请刷新后通过更正流程处理。',
  LOCK_CURRENT_GRADE_BEFORE_CORRECTION: '当前版本尚未锁定，请先核对并锁定。',
  ONLY_LATEST_GRADE_CAN_BE_LOCKED: '已有更新的评分版本，请刷新后核对。',
  ALL_RUBRIC_ITEMS_REQUIRED_ONCE: '请填写全部评分项，每项只提交一次。',
  RUBRIC_SCORE_OUT_OF_RANGE: '评分不能超过该项满分。',
  PANEL_NOT_READY: '请先保存两个方向相反、每组五人的评审组。',
  REVIEWER_NOT_IN_REVIEWER_CLASS:
    '评审人必须只属于指定评审班，不能同时在目标班。',
  REVIEWER_CLASS_CONFLICT: '评审人的班级归属发生冲突，请检查名单。',
  MATERIAL_CHECKS_PENDING: '仍有提交未完成材料检查，请等待检查结果。',
  SUBMISSION_DEADLINE_NOT_REACHED: '尚未到提交截止时间。',
  ANOMALY_NOT_OPEN_OR_NOT_FOUND: '这条异常已被处理，请刷新查看结论。',
  CLASS_ALREADY_EXISTS: '相同学期内已存在同名班级。',
  STUDENT_IDENTITY_CONFLICT:
    '学号已存在，但姓名或账号角色不匹配；导入已全部回滚。',
  NEW_STUDENT_PASSWORD_REQUIRED:
    '新账号必须填写至少10位初始密码；导入已全部回滚。',
  ENROLLMENT_IN_USE: '该学生已参与评审组或有提交记录，不能移出班级。',
  DEADLINE_MUST_BE_EXTENDED: '新截止时间必须晚于原时间和当前时间。',
  PUBLICATION_BLOCKED: '尚未满足发布条件，请处理页面列出的阻塞项。',
  NO_VALID_SUBMISSIONS: '没有可发布成绩的有效提交。',
  LATEST_GRADE_NOT_LOCKED: '最新教师评分未锁定',
  AGGREGATE_NOT_READY: '聚合结果尚未生成',
  TEACHER_SCORE_OUT_OF_RANGE: '教师评分数据超出量表范围，需要核查',
  AGGREGATE_OUT_OF_RANGE: '聚合分超出量表范围',
  AGGREGATE_STALE: '评审已更新，需要重新聚合',
  REVIEWS_INCOMPLETE: '五人评审尚未全部完成',
  MATERIAL_NOT_VALID: '材料检查尚未通过',
  OPEN_ANOMALIES_REQUIRE_REVIEW: '还有异常需要教师复核',
}
